import Head from "next/head";
import Home from ".";

import Layout from "../component/Layout";
import "../styles/globals.css";
import "../theme_html/theme/demo1/dist/assets/css/style.bundle";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>HispanoSoluciones.Com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HispanoSoluciones-Icons.ico" />
        <link
          href="assets/plugins/global/plugins.bundle.css"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="assets/css/style.bundle.css"
          rel="stylesheet"
          type="text/css"
        />
      </Head>

      <Layout>
        <Home {...pageProps} />
      </Layout>
    </>
  );
}

export default MyApp;
