/* eslint-disable @next/next/no-sync-scripts */
import Head from "next/head";
import Home from ".";

import Layout from "../component/Layout";
import "../styles/globals.css";
import "../theme_html/theme/demo1/dist/assets/css/style.bundle";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>HispanoSoluciones.Com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HispanoSoluciones-Icons.ico" />
        <link
          href="assets/plugins/global/plugins.bundle.css"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="assets/css/style.bundle.css"
          rel="stylesheet"
          type="text/css"
        />
      </Head>

      <Layout>
        <Home {...pageProps} />
      </Layout>

      <script>var hostUrl = "assets/";</script>

      <script src="assets/plugins/global/plugins.bundle.js"></script>
      <script src="assets/js/scripts.bundle.js"></script>

      <script src="assets/plugins/custom/fullcalendar/fullcalendar.bundle.js"></script>

      <script src="assets/js/custom/widgets.js"></script>
      <script src="assets/js/custom/apps/chat/chat.js"></script>
      <script src="assets/js/custom/modals/create-app.js"></script>
      <script src="assets/js/custom/modals/upgrade-plan.js"></script>
    </>
  );
}

export default MyApp;
